language: ruby
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of nokogiri

gemfile: docs/Gemfile

script:
  - cd docs
  - bundle exec jekyll build --baseurl=/mussy-notebook
  - cd ..

deploy:
  provider: pages
  local-dir: docs/_site/
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: main

sudo: false
